# Generated by Django 6.0.1 on 2026-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_digitalidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalidentity',
            name='digital_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
